# Generated by Django 5.0.4 on 2024-04-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_alter_quote_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='user',
            new_name='user_id',
        ),
    ]
