# Generated by Django 5.0.4 on 2024-04-25 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_rename_user_author_user_id_rename_user_quote_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='author of username',
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('user_id', 'fullname'), name='author of username'),
        ),
    ]
