# Generated by Django 5.0.4 on 2024-04-25 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0004_remove_author_author_of_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='author of username',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('user', 'fullname'), name='author of username'),
        ),
    ]
